### ISSUE TITLE
Adding Animation When hovering over different Genres

### ISSUE THREAD

**Issue by csills1416** [jonesmatr/What-2-Watch#23]
Tried adding a hover animation to the different genres on index.html. Nothing happened. Checked CSS and added ".card" and ".cardcolumn" nothing happened still.

**Comment by jonesmatr** [comment]
Can you copy and paste the code here so I can see what you were trying to do?

**Comment by csills1416** [comment]
For the Javascript:

    const genreCards = document.querySelectorAll('.card');

    genreCards.forEach(card => {
      card.addEventListener('mouseover', () => {
        card.classList.add('card-hover');
      });

      card.addEventListener('mouseout', () => {
        card.classList.remove('card-hover');
      });

But for the CSS:

.card {
  transition: transform 0.2s ease-in-out;
}

.card-hover {
  transform: scale(1.05);
}

**Comment by jonesmatr** [comment]
I got it to work. You were missing the 'event' parameter in the javascript code. See my corrections below.

const genreCards = document.querySelector('.card');

// Add a change event listener to the genre select on homepage
genreCards.forEach(card => {
    card.addEventListener('mouseover', event => {
      card.classList.add('card-hover');
    });

    card.addEventListener('mouseout', event => {
      card.classList.remove('card-hover');
    });
  });
