### ISSUE TITLE
Add Sub-Genres

### ISSUE THREAD

**Issue by csills1416** [jonesmatr/What-2-Watch#24]
When the USER wants a sub-genre instead of a genre,
Then the results will have sub-genres as well.

**Comment by jonesmatr** [comment]
What do you mean by sub-genre? The Utelly API doesn't have that as a parameter so we will not be able to search using that category.

**Comment by csills1416** [comment]
This was when we were talking with Darian. He suggested having sub categories as a feature but I think it'll be more of a headache to deal with in a short span of time.
